version: '3'
services:
  app:
    image: nextcloud:24-fpm
    restart: unless-stopped
    expose:
      - '80'
      - '9000'
    volumes:
      - nc_data:/var/www/html
    depends_on:
      - db
      - onlyoffice-server
    environment:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      PHP_UPLOAD_LIMIT:

  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  onlyoffice-server:
    image: onlyoffice/documentserver-ee:7.1
    restart: unless-stopped
    expose:
      - '80'
      - '443'
    volumes:
      - oo_data:/var/www/onlyoffice/Data
      - oo_logs:/var/log/onlyoffice

  nginx:
    image: nginx:1.23
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nc_data:/var/www/html

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 10000:8080

volumes:
  oo_data:
  oo_logs:
  nc_data:
  db_data:
